entry1=input('Enter text to write to the file: ')
file=open('output.txt','a')
appending_file=file.write(entry1+'\n')
print('Data successfully written to output.txt .\n')
file.close()
entry2=input('Enter additional text to append:')
file=open('output.txt','a')
appending_file1=file.write(entry2)
print('Data successfully appended. \n')
file.close()
print('Final content of output.txt: ')
file=open('output.txt','r')
reading_file=file.read()
print(reading_file)
file.close()